### ISSUE TITLE
`kubefedctl join` ignores `errorOnExisting=false` when `secretName` is provided

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes-sigs/kubefed#1009]
**What happened**: If I use `kubefedctl join`, say, in a Jenkins pipeline, and I provide the `--error-on-existing=false` flag, I would expect the command to be idempotent. When a secret name is not provided this is the actual behavior*, but when a secret is provided the join command exits with a non-zero code reporting `secrets "[secret name]" already exists`.

This might be intended behavior because there's nothing stopping someone using a previously used secret name to join a new cluster.

*sort of - a new secret is created with a generated name

**What you expected to happen**: The join command would ignore the fact that the secret already exists because I provided the `--error-on-existing=false` flag. I should be able to re-run that same command as many times as I like and it would not throw an error (assuming all the arguments are valid and all clusters are reachable etc).

**How to reproduce it (as minimally and precisely as possible)**:
Run this command 2 times:
```
kubefedctl join \ 
  [cluster-name]
  --cluster-context [cluster-context]
  --host-cluster-context [host-cluster-context]
  --secret-name *some-secret-name*
  --error-on-existing=false
```

**Anything else we need to know?**: Curious how this should be resolved. In the `populateSecretInHostCluster` function (join.go) the presence of the secret in the host cluster is not checked. Let's say we attempt to get the secret and get an `IsNotFound(err)==true`, then we can continue as normal. If we do find a secret and errorOnExisting=false, we have a couple of ways forward:
- Just return that same secret from the populateSecretInHostCluster function
- The secret could be stale - delete it and then create it again using the current code path

**Environment**:
- Kubernetes version (use `kubectl version`) client: v1.13.1, server: v1.13.4
- KubeFed version v0.1.0-rc2
- Scope of installation (namespaced or cluster) cluster I think
- Others

/kind bug

**Comment by marun** [comment]
I believe this was the intended behavior to avoid overwriting an existing secret. Note that `--error-on-existing=false` is the default, so a user would be in danger of overwriting an existing secret without specifying the argument explicitly.

The current behavior of join is not really idempotent - iirc the intent was to allow repeated invocation until a join was successful (i.e. in case of transient failures). Once a join was successful, subsequent join invocations either break (as you are noticing, if the secret name was specified) or create a new secret without removing the old one (in the case of not specifying a name and a generated one being used).  I don't think either behavior is desired.

Can you share more detail as to your use case for join being truly idempotent? I'm wondering if instead a successfully joined cluster should fail subsequent re-joining (i.e. the existing joined cluster would need to be unjoined before re-joining) or if join should be smart enough to know that a previous join was successful so that a secret referenced by the `KubeFedCluster` instances could be updated rather than deleted or rendered unnecessary by a new secret.

**Comment by andrewmyhre** [comment]
In our use-case we're importing the kubefed module into a proprietary provisioner we've developed similar to kops (long story). We'd like to have it join a cluster to a host cluster during provisioning. Our provisioning process is intended to be idempotent so that we can use it as a driver for Gitops-style infrastructure updates. Hence the desire is for a 0 exit code when nothing needs to be done.

The current behavior does make sense to me. There isn't really a reliable way to determine whether the existing secret is for cluster A or cluster B, so it's prudent to fail with an error. 

How about, in the case that a secret already exists, we look up the control plane url on the existing cluster and compare with the one joining. If it's the same we can assume we're just running another join command on the same cluster and we can do nothing and exit, or delete and recreate the secret as the token may have been rotated since the last join. If the control plane urls are different we exit with a (meaningful) error.

**Comment by andrewmyhre** [comment]
Maybe the check could be added to the `performPreflightChecks` func?

**Comment by andrewmyhre** [comment]
Here's a proposal: https://github.com/andrewmyhre/kubefed/pull/1

**Comment by marun** [comment]
> Here's a proposal: [andrewmyhre#1](https://github.com/andrewmyhre/kubefed/pull/1)

Thank you for posting, will review shortly!
