### ISSUE TITLE
Create an easily consumable release yaml for each kubefed release

### ISSUE THREAD

**Issue by abhat** [kubernetes-sigs/kubefed#1014]
**What would you like to be added**: Create a release yaml artifact that can be easily consumed by users that don't deploy KubeFed via Helm charts.

**Why is this needed**: Currently, every time there are changes to the CRDs for a given release, those changes are only made in the Helm charts directories. However, for a user that wants to deploy KubeFed (either via the kubefed-operator or otherwise without Helm charts), there is no release yaml provided.

As far as deployment of KubeFed as an operand via kubefed-operator is concerned, it is desirable to reduce the friction in maintaining newer CRDs per release between the operator repo (github.com/openshift/kubefed-operator) and those under this repo. 

/kind feature

**Comment by abhat** [comment]
cc @pmorie @marun

**Comment by marun** [comment]
@abhat I'm not sure it should be desirable to release such an artifact. The tree used to create the yaml is tagged, and the creation is entirely mechanical (using either `go generate` or `kubefedctl enable`).  Also, the operator may want to run `kubefedctl enable` aagainst an openshift cluster rather than kubernetes.
