### ISSUE TITLE
Basic walkthrough and associated test script

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubefed#104]
There should be a relatively simple walkthrough that guides users through the experience of kicking the tires on federation-v2 by deploying a very simple application. Other attributes of this:

- Should be possible to do using just minikube (ie, no cloud provider required)
- Should cover installing federation and adding new clusters into a federation
- There should be a test script that exercises the walkthrough and ensures that the walkthrough 'works'.

**Comment by font** [comment]
> - Should be possible to do using just minikube (ie, no cloud provider required)
> - Should cover installing federation and adding new clusters into a federation
> - There should be a test script that exercises the walkthrough and ensures that the walkthrough 'works'.

I think the first 2 bullet points are more-or-less already covered by #84 depending on what you mean by a *simple* application. I think the 3rd bullet point is what still needs to be done.

**Comment by xunpan** [comment]
@pmorie 
What does your walkthrough means for a script?
From my understanding, below `kubectl` command line is enough to deploy a simple federation resource. 
```
kubectl apply -f example/sample1/federatednamespace.yaml
kubectl apply -f example/sample1/federateddeployment.yaml
```

**Comment by marun** [comment]
I think a script is suggested because the existing walkthrough is not sufficient.  A revised walkthrough would ideally include something like the following:

 - apply yaml to create a namespace and resources in that namespace that comprise a web service (i.e. create a non-federated microservice)
 - federate the application with `kubefed federate ns --contents ` (e.g. #741)
 - check the propagation status of the deployment with `kubectl get federateddeployment -n <ns> myns` (e.g. #843)
 - check that the web service is healthy (e.g. via curl) on the clusters
 - adjust the propagation (e.g. remove one cluster) and check the propagation status and check with curl
 - change an override (e.g. have the message the web service returns be configured via configmap, adjust the value in the configmap with an override, and check that the message the service returns on the cluster has changed)
