### ISSUE TITLE
Helm Chart Failed Installation with Helm 3

### ISSUE THREAD

**Issue by jishminor** [kubernetes-sigs/kubefed#1143]
**What happened**:
Helm chart fails to install with error:
```
manifest_sorter.go:179: info: skipping unknown hook: "crd-install"
...
Error: apiVersion "core.kubefed.io/v1beta1" in kubefed/charts/controllermanager/templates/kubefedconfig.yaml is not available
```

When installed using command:
```
helm install kubefed-charts/kubefed --name-template kubefed --version=0.1.0-rc6 --namespace kube-federation-system
```

It appears that the crd-hook in the chart is potentially failing. Could be an issue with helm 3 crd-hooks.  

**What you expected to happen**:
Successful installation of kubefed chart.

**How to reproduce it (as minimally and precisely as possible)**:
- Install helm 3 via release page on their github. 
- Configure kubeadm cluster with weavenet cni plugin.
- Attempt to install chart using command listed above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: Client 1.11, Server 1.15
- KubeFed version: 0.1.0-rc6
- Scope of installation: cluster

/kind bug

**Comment by jishminor** [comment]
Some other interesting notes:

When using helm 3.0.0-alpha.1, I verified that if you take the controller-manager [crd yaml](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/charts/controllermanager/templates/crds.yaml) and just manually apply it as a file, then the api group is created properly. However installing the helm chart fails with the same error.

Having upgraded to helm 3.0.0-beta.3, I applied the crd manually as before to create the api resources, then ran helm install, and it complained that the kube-federation-system namespace didn't exist. I then created that namespace manually, re-ran the helm install command, and the control-plane finally deployed successfully.

**Comment by font** [comment]
We only support deployment with helm 2 at the moment, especially since helm 3 is not officially released yet (still in beta). Despite that, since the `crd-install` hook is used to request helm to install the CRD resources early so that other resources can depend on them, helm 3 should provide the same, or similar, facility to guarantee this. I'm not aware of the backwards compatibility guarantees of helm 3 with helm 2. But if backwards compatibility is a goal, then this should be filed as a bug against helm 3.

For the other error, creating the kube federation system namespace is part of the helm chart installation command https://github.com/kubernetes-sigs/kubefed/tree/master/charts/kubefed#installing-the-chart. Did you provide the namespace argument when testing with the latest helm 3 beta? If so, that sounds like a bug with helm 3.

**Comment by jishminor** [comment]
I have seen a few issues floating around surrounding the crd-install features of helm. I will go ahead and file these issues in the helm repository with references back to this thread.

As for the namespace issue, I most certainly had the namespace set as an argument when installing. I'm sure in the coming months helm 3 will be out of beta, and hopefully many of these issues will be resolved. I will say it is really nice to not have to deal with a tiller installation in your cluster to install the kubefed control-plane.

**Comment by jishminor** [comment]
Upon reading the release notes for helm 3 beta:

![image](https://user-images.githubusercontent.com/16505634/64456503-f768a880-d0b5-11e9-8b7c-2b3efb316408.png)

Looks like this is the culprit for the issues above.
