### ISSUE TITLE
service.spec.ports is overrided

### ISSUE THREAD

**Issue by coldTea214** [kubernetes-sigs/kubefed#1158]
**What happened**:

according to your document: https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#local-value-retention, sync controller won't overrides service.spec.ports field. But in my test, this field is overrided.

**What you expected to happen**:

service.spec.ports is not overrided

**How to reproduce it (as minimally and precisely as possible)**:

* create a federated service
* modify spec.ports in federated service templates
* service in cluster will be modified

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
1.14.1
- KubeFed version
v0.1.0-rc6
- Scope of installation (namespaced or cluster)
cluster
- Others

/kind bug

**Comment by marun** [comment]
It appears that the documentation is misleading. The entirety of the `ports` field is not retained - rather, the `nodePort` values are retained (since they are supplied by a controller local to the member cluster). I don't think it would be desirable to prevent all changes to the ports field after creation in member clusters.

**Comment by coldTea214** [comment]
thanks
