### ISSUE TITLE
Kubefed roadmap and GA dates

### ISSUE THREAD

**Issue by Gaploid** [kubernetes-sigs/kubefed#1312]
Hi,
Im really like the KubeFed project and see a lot of potential in that tech especially in hybrid scenarios but me and my customers are wondering about unclear GA dates and the roadmap. I know thats a hard question and its hard to commit to something like that but probably you can share any information on when it would be ready to use in production scenarios or any approximate dates/roadmap?

/triage support

**Comment by hectorj2f** [comment]
@Gaploid We are actively using and maintaining kubefed. In addition, we have proposed certain improvements that we want to include into kubefed. 

Some of those improvements are:

* Remote federated resource status: https://github.com/kubernetes-sigs/kubefed/blob/master/docs/keps/20200619-federated-resource-status.md
* Pull reconciliation model: https://github.com/kubernetes-sigs/kubefed/blob/master/docs/keps/20200619-kubefed-pull-reconciliation.md
* Certain experimental features would be deprecated which would help to keep the code cleaner and ease the maintenance. 
* With a clear focus on the main kubefed features (resource federation), we could easily increase the test coverage.

Did I miss anything @makkes ?

Our idea is to come with a more official ROADMAP and share it during the sig-meeting, cc @jimmidyson.

**Comment by Gaploid** [comment]
That's great. Any ideas of multi-deployment of kubefed to remove a single point of failure? As I understand currently kubefed deployed on one "master" cluster and if it will go down all federation will be de-synced.

**Comment by hectorj2f** [comment]
@Gaploid That is an interesting topic, I've been reading related work that shards the control plane across the cluster or clusters to solve that problem. We could kick the discussion in a KEP if you also have ideas but I don't think it is part of the imminent roadmap.

In relation to your comment, ` if it will go down all federation will be de-synced`, there won't be such de-synced because the kubefedcluster will keep their state as defined before the control-plane or master clsuter crashed. 
Generally if you have a HA setup for your etcd datastore you could face downtimes if the kubefed control-plane pods go down, but the state would remain in etcd. You could have etcd peers in different AZs to avoid facing these issues.
