### ISSUE TITLE
create  federatedcustomresourcedefinitions, but found ` Failed to watch apiextensions.k8s.io/v1` error, all CR is created in host cluster

### ISSUE THREAD

**Issue by CharlesQQ** [kubernetes-sigs/kubefed#1350]
I want to federate CRD & CR, but found error, the host cluster version is k8s 1.18, member cluster version is k8s 1.10
here is error log

E0128 16:18:15.823707      39 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch apiextensions.k8s.io/v1, Kind=CustomResourceDefinition: failed to list apiextensions.k8s.io/v1, Kind=CustomResourceDefinition: the server could not find the requested resource
E0128 16:18:38.518458      39 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch apps.eagle.io/v1alpha1, Kind=PhpSidecarSet: failed to list apps.eagle.io/v1alpha1, Kind=PhpSidecarSet: the server could not find the requested resource

**Comment by hectorj2f** [comment]
@CharlesQQ I don't know where these errors are prompted but I assume the problem might come with the usage of deprecated or new api versions that might not be available on 1.10. 

We have not used kubefed with clusters whose kubernetes version differed so much. Many of the federated types in the kubefed control plane cluster won't work on the managed clusters due to the usage or newer api versions than are not present in 1.10.

**Comment by yuswift** [comment]
I guess you need to upgrade your member cluster version to v1.18(same as the host cluster).
