### ISSUE TITLE
Support restricting access to certain clusters

### ISSUE THREAD

**Issue by tghartland** [kubernetes-sigs/kubefed#524]
For the CERN use case of running many different types of workload in a large federation of clusters, restricting access to certain classes of cluster does a few things for us (and lets us use a very simple placement to schedule everywhere else).

- Mainly it lets us reserve clusters with particular hardware for only workloads that require that hardware, i.e GPU clusters or for clusters with especially large nodes. 
- In our own cloud it would also let us restrict access to any clusters we create in our critical power area.

Point number 1 would be possible with separate federations (but would probably lead to too much fragmentation), and for point number 2 deployments should be in both standard and critical power, so separate federations would require managing multiple copies of the deployment.

- It would also be one way to designate if a job is important enough to send to an external cloud if our own is at capacity. Some jobs would be fine left in pending until there is room for them.

In the November 21st federation-v2 meeting, taints/tolerations were suggested as the best way to support this. I have started on an implementation for this in #515.

If there is a simpler way to do this then I'm all ears, because the full feature set of taints/tolerations is actually a bit overkill for this. Since these things (hardware/location) are immutable properties of the cluster, it is unlikely that we would need the NoExecute taint, and PreferNoSchedule is possibly covered by cluster weightings in placement. Encoding in the name (i.e starts with "+") that a label is required in the placement to schedule on that cluster would be one possible solution, but I assume that diverging from standard kubernetes behaviour is to be avoided at all costs.

When I say restrict I realise that this is not enforceable ([yet](https://github.com/kubernetes/kubernetes/issues/48041)) but it is just to mean that the particular clusters are opt-in to schedule on.

**Comment by marun** [comment]
I apologize for taking so long to respond to this, I've been away.  I appreciate your taking the time to document your use case, and I think I have a better grasp of your motivation for #515.  

- I think it unfortunate that `kubectl taint` is restricted to targeting nodes, since the logic would seem to readily apply to a `FederatedCluster` that has the same `Taints` field.

- I think you're correct that the semantics of label selection should remain unchanged from Kubernetes.

- Assuming a goal of opt-in placement, I think you're on the right path.

- #526 seems to be describing a related use case, in which access to member clusters needs to segmented by user.  I'm curious if the namespace placement change described in [a comment](
https://github.com/kubernetes-sigs/federation-v2/issues/526#issuecomment-449496474) on that issue might be helpful to your use case.

**Comment by tghartland** [comment]
For your proposal in that comment, I think it would technically work but is really suited to only a single parameter i.e separating based on ownership of clusters as suggested there. With each created resource being limited to a single namespace, for arbitrary combinations of multiple parameters the number of namespaces required would be too many to find concise names for and keep track of.

I also don't particularly like the idea of forcing namespaces to be used like this. To separate out resources within each "placement namespace" you'd then need copies of the namespaces but with a unique app name or whatever added on to the end of the namespace name.

**Comment by marun** [comment]
@tghartland I should clarify that my pointer to #526 was more to raise the possibility of defining authz permissions for clusters such that users would have to be authorized to propagate to a given cluster.  I agree that namespaces as the mechanism for association is not in keeping with what you're trying to do.
