### ISSUE TITLE
Support selector-based overrides

### ISSUE THREAD

**Issue by jewzaam** [kubernetes-sigs/kubefed#581]
**What would you like to be added**:
Ability to define a `clusterSelector` on all Federated<Type>Override objects.

**Why is this needed**:
We plan to manage many clusters with Hive + Federation.  Rollout of changes is expected to be managed by groups of clusters, such as dev, test, stage, production though I expect it to be more varied.  In order to do this, it looks like overrides are a good option.  But having to specify the override by `clusterName` will require tooling at the time of creating and modifying clusters.  Having this based on a selector will move management to labels on the `FedereatedCluster`.

/kind feature

**Comment by xunpan** [comment]
This case makes sense to me. We've already had clusterSelector in placement. It should be useful to make it in override in similar way. 

@marun any comments?

**Comment by jewzaam** [comment]
I've been trying out overlaps with the existing mechanism and cannot figure out how it's reported as an error yet.  I see in the source it should report that the `clusterName` "appears more than once" but when I test this with duplicate overrides for a configMap there's no reference in anything I can think to check.  I'm looking in federation-controller-manager logs and the following CRs:  FederatedCluster, FederatedConfigMap, FederatedConfigMapPlacement, FederatedConfigMapOverride.

Given this behavior, that overlap in override is an error state, could the same not be done if `clusterSelector` were supported?

**Comment by marun** [comment]
I think it's preferable to minimize the potential for errors in the default case.  Bulking up the core API to support every use case is not desirable - it's easy to add and hard to take away.  I consider your use case as a nice-to-have and something that can be implemented on top of the existing API rather than as part of it.  If in the future it becomes clear that it is an essential feature used by a representative subset of the users, then it would be a candidate for inclusion in the core API.

**Comment by marun** [comment]
To be clear, `clusterNames` may contain duplicate cluster names but if that happens the resolution should really be to ignore the duplicate names rather than raising an error.  The same easy path to resolution is not possible for competing overrides and would require an error.  That seems like a footgun to me, and I'd rather see that behavior delivered as an optional add-on until it is proven otherwise.

**Comment by jewzaam** [comment]
Fair point on detection up front being impossible with a selector.  It's a mutable state.  

I observed that duplicate cluster name would cause a silent failure.  I'll create a separate issue for that.

On resolution being easy, how can you know which version of the override is desired in either case?  Is there a generally approved pattern for which to ignore?  I could see it being a problem either way you choose to go depending on the way they're added by whoever maintains the override.  How about raising an alert via prometheus and let the customer decide what to do?  At least in the duplicate `clusterName` case it's likely you'd find out very soon after making the change.  And while I'd like the ability to do the same with `clusterSelector`, the ops experience could be pretty bad.

**Comment by marun** [comment]
@jewzaam Currently crd validation requires deploying webhooks, and we've avoided implementing one to handle things like override validation just yet because of the complexity of cert handling.  I'm expecting, though, that webhook deployment is going to become easy at some point and then we can validate duplicates in overrides on creation/updates of a federated type.

**Comment by marun** [comment]
Determination of whether a resource in a member cluster needs to be updated is currently dependent on the contents of the overrides field being hashed and compared with the hash most recently used to update the resource.  Implementing selector-based overrides would require either hashing the entire resource computed for the update or hashing the overrides field after expanding any selectors.  There are performance implications for both options, and both will be more complicated to implement than selector-based placement.

**Comment by gyliu513** [comment]
@marun @jewzaam can you please update the title a bit by removing `Federated<Type>`?

**Comment by mvaal** [comment]
/reopen

Between this https://github.com/kubernetes-sigs/kubefed/pull/1010 and this not being implemented, we are in an annoying situation.
Trying to using charts that requires annotations (e.g., https://github.com/mittwald/kubernetes-replicator)
and having to continually to update the overrides list for every single cluster doesn't seem like a great solution.
We would need an operator that updates the Federated<Object> with the overrides every time a new federatedcluster is added/deleted. Doesn't seem right to have to write operators to bypass something like this.
