### ISSUE TITLE
It should not be possible to join a cluster multiple times

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#749]
With the update to `kubefed2 join` to support idempotency (#555), it is now possible to join a cluster multiple times without error (unless `--error-on-existing` is supplied).  If this were done accidentally, the sync controller could end up fighting itself if the placement or overrides for duplicated clusters differed.

Possible fixes:

 - update join to be optionally idempotent so that existing resources would stop the join
 - add logic to join to detect when more than one cluster is using the same api endpoint
 - add logic to the cluster controller to detect when more than one cluster is using the same api endpoint

**Comment by marun** [comment]
It may also make sense for `kubefed2 join` (without a cluster name argument) to list available contexts in the local kubeconfig as well as indicate which contexts have already been joined.

**Comment by 11janci** [comment]
Hi,
I'd take this, however need to clarify couple of questions:

* `update join to be optionally idempotent so that existing resources would stop the join`
Currently if you try to add a cluster with a name that already exists, it either overwrites the existing spec (default) or fails (if the `--error-on-existing` flag is set). So if I understand correctly, you'd like to simply terminate the join operation instead? If so, should this be a default behaviour?

* `add logic to join to detect when more than one cluster is using the same api endpoint`
If I understand this correctly, this would involve getting a list of all the joined clusters and checking that the endpoint is not the same as the one being added?

Thanks!

**Comment by marun** [comment]
@11janci Your interest is much appreciated.  I would like to see validation that a given api endpoint is used at most once in a kubefed control plane.  I think that check belongs in an admission webhook for `KubeFedCluster` (an initial version of which is proposed in #862).  If you wanted to work on this I suggest branching #862 and adding a check that queries other `KubeFedCluster` resources and ensures that creation or update of an instance is only permitted for a unique endpoint.

**Comment by 11janci** [comment]
thanks, will look into it.

**Comment by 11janci** [comment]
Hi @marun ,
I finally managed to look into this. I can add a validation to the admission webhook, however it won't be bulletproof as there will always be a race condition where two clusters with the same endpoint can be added if the join requests happen close enough to each other. I don't see a simple solution to this. The most viable probably would be including a check for duplicates in the ClusterController. Question is, what should happen if a duplicate is found - should we unjoin the cluster?
Alternative solution would be storing the endpoints as API objects themselves, which would by definition prevent duplicates. This would however duplicate stored data and complicate the join/unjoin ops.
Let me pls know what you think.

**Comment by marun** [comment]
@11janci I think this may need to wait until the Cluster ID initiative (ensuring a unique and immutable cluster identifier) bears fruit.  Neither a unique API endpoint, server cert or token would guarantee the identity of a cluster (especially over time).

**Comment by 11janci** [comment]
hey @marun, ok agreed, probably makes sense to wait then.
