### ISSUE TITLE
Leverage kubernetes/test-infra for federation v2 CI

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubefed#846]
**What would you like to be added**:
It is better to enable federation v2 also leverage `kubernetes/test-infra` to do the CI checking, please refer to https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs for detail.

/cc @marun @xunpan 

**Why is this needed**:

/kind feature

**Comment by marun** [comment]
A past blocker for adopting prow was this repo's dependency on a deployed cluster.  kind is now supported by prow, but now we're dependent on multiple deployed clusters.  Does prow support multiple kind clusters for a job?

Also, prow is very different from travis in that it is based on containers rather than images.  This move to a more 'immutable' approach to our CI infrastructure is potentially more complicated than travis' vm-based approach.

A move to prow may be inevitable on a long-enough timeline, but I think the timing of a move should be carefully considered.  We have a workable solution today. Until travis becomes more trouble than its worth, or we end up requiring things that only prow can provide, I'm not sure the effort to switch would be justified.
