### ISSUE TITLE
control plane on multiple clusters

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/kubefed#967]
This might be an documentation issue - currently it's not clear if the control plane can be hosted in multiple clusters or not - documentation should state that it is not supported.

If so, then can the control plane be moved to another cluster? The docs should also cover that.

/kind docs

**Comment by marun** [comment]
No, the control plane cannot be hosted on multiple clusters.  KubeFed provides Kubernetes API types and controllers that run on a single cluster, just like any other Kube service.  Running simultaneously on multiple clusters would require exposing a non-Kube API backed by a distributed data store (and probably not etcd depending on latency between clusters).

Since #636 has already been filed to cover the topic of disaster recovery (which encompasses the topic of migration of the control plane), I think this issue can likely be closed as a duplicate.
