### ISSUE TITLE
Generated federated types should set preserveUnknownFields to false

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#986]
An issue like #984 is the result of Kube not stripping unknown fields when accepting a request to add or update a custom resource. Kube 1.15 will add support for stripping unknown fields by setting `spec.preserveUnknownFields: false`, and this should be supported for generated federated types when running on kube 1.15.

**Comment by xunpan** [comment]
CRD v1 will pruning unknown field by default.
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#pruning-versus-preserving-unknown-fields
```
CustomResourceDefinitions store validated resource data in the cluster's persistence store, etcd. As with native Kubernetes resources such as ConfigMap, if you specify a field that the API server does not recognize, the unknown field is pruned (removed) before being persisted.
```

I checked in `kubefed`, it follows the behavior. When I tried to add unknown field, it was rejected. That means this issue is fixed.
```
# federateddeployments.types.kubefed.io "test-deployment" was not valid:
# * : Invalid value: "The edited file failed validation": ValidationError(FederatedDeployment.spec.placement): unknown field "clusterNames" in io.kubefed.types.v1beta1.FederatedDeployment.spec.placement
#
```

So, close this ticket.

/close
